<?php
$LoginCaptchaForm->prepare();

echo $this->doctype();
?>
<html lang="en">
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8">
	<meta charset="utf-8">
    <?php echo $this->headTitle('NotaryToolz - Member Access.')->setSeparator(' - ')->setAutoEscape(false) ?>

	<?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=no')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge,IE=9,IE=8,chrome=1')
        ->appendName('description', '')
        ->appendName('author', '')
    ?>

	<?php echo $this->headScript()
        ->prependFile('http://css3-mediaqueries-js.googlecode.com/svn/trunk/css3-mediaqueries.js'   , 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile('http://html5shiv.googlecode.com/svn/trunk/html5.js'                          , 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/admin/js/flot/excanvas.min.js'                           , 'text/javascript', array('conditional' => 'lt IE 9',))
    ; ?>

    <?php echo $this->headLink
                    (
                        array
                        (
                            'rel'   =>  'shortcut icon',
                            'type'  =>  'image/vnd.microsoft.icon',
                            'href'  =>  $this->basePath() . '/application/images/favicon.ico'
                        )
                    )
                    ->prependStylesheet($this->basePath() . '/notarytoolz/auth-view/auth/auth/css/login-captcha.css')
                    ->prependStylesheet('http://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700')
                    ->prependStylesheet($this->basePath() . '/admin/css/animatecss/animate.min.css')
                    ->prependStylesheet($this->basePath() . '/admin/js/uniform/css/uniform.default.min.css')
                    ->prependStylesheet($this->basePath() . '/admin/js/bootstrap-daterangepicker/daterangepicker-bs3.css')
                    ->prependStylesheet($this->basePath() . '/admin/font-awesome/css/font-awesome.min.css')
                    ->prependStylesheet($this->basePath() . '/admin/css/cloud-admin.css')
    ?>






</head>
<body class="login">
	<!-- PAGE -->
	<section id="page">
			<!-- HEADER -->
			<header>
				<!-- NAV-BAR -->
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-md-offset-4">
							<div id="logo">
								<a href="<?php echo $this->url('home'); ?>"><img src="<?php echo $this->basePath(); ?>/admin/img/logo/notarytoolz-logo.png" height="60" alt="logo name" /></a>
							</div>
						</div>
					</div>
				</div>
				<!--/NAV-BAR -->
			</header>
			<!--/HEADER -->
			<!-- LOGIN with ReCAPTCHA-->
			<section id="login" class="<?php echo ($PauseGifDisplaySeconds > 0 ? '' : 'visible'); ?>">
				<div class="container">
					<div class="row">
						<div class="col-md-4 col-md-offset-4">
							<div class="login-box-plain">
								<h2 class="bigintro">Member Login</h2>

                                <?php if($LoginFormMessages != '' || $LoginCaptchaFormMessages != '' || $reCaptchaError || $LoginAttemptMessage != '' || $LoginCaptchaAttemptMessage != ''): ?>
                                <div class="alert alert-block alert-danger fade in">
                                    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">×</a>
                                    <h4><i class="fa fa-times"></i> Oh snap! You got an error!</h4>
                                    <?php

                                        if($LoginCaptchaFormMessages != '')
                                        {
                                            echo $this->formElementErrors()
                                                    ->setMessageOpenFormat('<ul><li>')
                                                    ->setMessageSeparatorString('</li><li>')
                                                    ->setMessageCloseString('</li></ul>')
                                                    ->render($LoginCaptchaForm)
                                            ;
                                        }

                                        if($LoginFormMessages != '')
                                        {
                                            echo $this->formElementErrors()
                                                    ->setMessageOpenFormat('<ul><li>')
                                                    ->setMessageSeparatorString('</li><li>')
                                                    ->setMessageCloseString('</li></ul>')
                                                    ->render($LoginCaptchaForm)
                                            ;
                                        }

                                        if($reCaptchaError)
                                        {
                                            echo '<ul><li>Incorrect Captcha Value. Please retry.</li></ul>';
                                        }

                                        if($LoginAttemptMessage != '')
                                        {
                                            echo '<ul><li>' . $LoginAttemptMessage . '</li></ul>';
                                        }

                                        if($LoginCaptchaAttemptMessage != '')
                                        {
                                            echo '<ul><li>' . $LoginCaptchaAttemptMessage . '</li></ul>';
                                        }
                                    ?>
                                </div>
                                <?php endif; ?>


								<div class="divide-40"></div>

                                    <?php

                                        echo $this->form()->openTag($LoginCaptchaForm);
                                        echo $this->formHidden($LoginCaptchaForm->get('login_captcha_csrf'));
                                    ?>

                                        <input class="siteInput Input1" name="usr"          type="text"  value="">
                                        <input class="siteInput Input2" name="username"     type="text"  value="">
                                        <input class="siteInput Input3" name="email"        type="text"  value="">
                                        <input class="siteInput Input4" name="login_email"  type="text"  value="">

                                        <div class="form-group">
                                            <?php echo $this->formLabel($LoginCaptchaForm->get('returning_member')); ?>
                                            <i class="fa fa-envelope"></i>
                                            <?php echo $this->formInput($LoginCaptchaForm->get('returning_member')); ?>
                                        </div>
                                        <div class="form-group">
                                            <?php echo $this->formLabel($LoginCaptchaForm->get('LoginCaptchaFormPasswordField')); ?>
                                            <i class="fa fa-lock"></i>
                                            <?php echo $this->formInput($LoginCaptchaForm->get('LoginCaptchaFormPasswordField')); ?>
                                        </div>
                                        <div class="form-actions">
                                            <?php echo $reCaptcha->getHtml(); ?>
                                        </div>
                                        <div class="form-actions">
                                            <button type="submit" class="btn-lg btn-danger">Login</button>
                                        </div>
                                    <?php
                                        echo $this->form()->closeTag($LoginCaptchaForm);
                                    ?>

								<!-- SOCIAL LOGIN
								<div class="divide-20"></div>
								<div class="center">
									<strong>Or login using your social account</strong>
								</div>
								<div class="divide-20"></div>
								<div class="social-login center">
									<a class="btn btn-primary btn-lg">
										<i class="fa fa-facebook"></i>
									</a>
									<a class="btn btn-info btn-lg">
										<i class="fa fa-twitter"></i>
									</a>
									<a class="btn btn-danger btn-lg">
										<i class="fa fa-instagram"></i>
									</a>
								</div>
								/SOCIAL LOGIN -->
							</div>
						</div>
					</div>
				</div>
			</section>
			<!--/LOGIN -->
	</section>
	<!--/PAGE -->

    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/notarytoolz/auth-view/auth/auth/js/recaptcha.js'                     , 'text/javascript', array())
        ->prependFile($this->basePath() . '/notarytoolz/auth-view/auth/auth/js/login-captcha.js'                 , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/js/script.js'                                                  , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/js/uniform/jquery.uniform.min.js'                              , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/bootstrap-dist/js/bootstrap.min.js'                            , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/js/jquery-ui-1.10.3.custom/js/jquery-ui-1.10.3.custom.min.js'  , 'text/javascript', array())
        ->prependFile($this->basePath() . '/admin/js/jquery/jquery-2.0.3.min.js'                                 , 'text/javascript', array())
    ; ?>

    <script>
		jQuery(document).ready(function() {		
			App.setPage("login");  //Set current page
			App.init(); //Initialise plugins and elements
		});
	</script>
	<script type="text/javascript">
		function swapScreen(id) {
			jQuery('.visible').removeClass('visible animated fadeInUp');
			jQuery('#'+id).addClass('visible animated fadeInUp');
		}
	</script>
	<!-- /JAVASCRIPTS -->
</body>
</html>